const library = [
{
  "author": "E. E. Cummings",
  "text": [
    "i carry your heart with me(i carry it in",
    "my heart)i am never without it(anywhere",
    "i go you go,my dear;and whatever is done",
    "by only me is your doing,my darling)",
    "i fear",
    "no fate(for you are my fate,my sweet)i want",
    "no world(for beautiful you are my world,my true)",
    "and it\u2019s you are whatever a moon has always meant",
    "and whatever a sun will always sing is you",
    "here is the deepest secret nobody knows",
    "(here is the root of the root and the bud of the bud",
    "and the sky of the sky of a tree called life;which grows",
    "higher than soul can hope or mind can hide)",
    "and this is the wonder that's keeping the stars apart",
    "i carry your heart(i carry it in my heart)"
  ],
   "title": "[i carry your heart with me(i carry it in]"
},
{
  "author": "E. E. Cummings",
  "text": [
    "love is more thicker than forget",
    "more thinner than recall",
    "more seldom than a wave is wet",
    "more frequent than to fail",
    "it is most mad and moonly",
    "and less it shall unbe",
    "than all the sea which only",
    "is deeper than the sea",
    "love is less always than to win",
    "less never than alive",
    "less bigger than the least begin",
    "less littler than forgive",
    "it is most sane and sunly",
    "and more it cannot die",
    "than all the sky which only",
    "is higher than the sky"
  ],
  "title": "[love is more thicker than forget]"
},
{
  "author": "E. E. Cummings",
  "text": [
    "as freedom is a breakfastfood",
    "or truth can live with right and wrong",
    "or molehills are from mountains made",
    "\u2014long enough and just so long",
    "will being pay the rent of seem",
    "and genius please the talentgang",
    "and water most encourage flame",
    "as hatracks into peachtrees grow",
    "or hopes dance best on bald men",
    "s hair",
    "and every finger is a toe",
    "and any courage is a fear",
    "\u2014long enough and just so long",
    "will the impure think all things pure",
    "and hornets wail by children stung",
    "or as the seeing are the blind",
    "and robins never welcome spring",
    "nor flatfolk prove their world is round",
    "nor dingsters die at break of dong",
    "and common\u2019s rare and millstones float",
    "\u2014long enough and just so long",
    "tomorrow will not be too late",
    "worms are the words but joy\u2019s the voice",
    "down shall go which and up come who",
    "breasts will be breasts thighs will be thighs",
    "deeds cannot dream what dreams can do",
    "\u2014time is a tree(this life one leaf)",
    "but love is the sky and i am for you",
    "just so long and long enough"
  ],
  "title": "[as freedom is a breakfastfood]"
},
{
  "author": "E. E. Cummings",
  "text": [
    "anyone lived in a pretty how town",
    "(with up so floating many bells down)",
    "spring summer autumn winter",
    "he sang his didn\u2019t he danced his did.",
    "Women and men(both little and small)",
    "cared for anyone not at all",
    "they sowed their isn\u2019t they reaped their same",
    "sun moon stars rain",
    "children guessed(but only a few",
    "and down they forgot as up they grew",
    "autumn winter spring summer)",
    "that noone loved him more by more",
    "when by now and tree by leaf",
    "she laughed his joy she cried his grief",
    "bird by snow and stir by still",
    "anyone\u2019s any was all to her",
    "someones married their everyones",
    "laughed their cryings and did their dance",
    "(sleep wake hope and then)they",
    "said their nevers they slept their dream",
    "stars rain sun moon",
    "(and only the snow can begin to explain",
    "how children are apt to forget to remember",
    "with up so floating many bells down)",
    "one day anyone died i guess",
    "(and noone stooped to kiss his face)",
    "busy folk buried them side by side",
    "little by little and was by was",
    "all by all and deep by deep",
    "and more by more they dream their sleep",
    "noone and anyone earth by april",
    "wish by spirit and if by yes.",
    "Women and men(both dong and ding)",
    "summer autumn winter spring",
    "reaped their sowing and went their came",
    "sun moon stars rain"
  ],
  "title": "[anyone lived in a pretty how town]"
},
{
  "author": "Emily Dickinson",
  "text": [
    "Because I could not stop for Death \u2013",
    "He kindly stopped for me \u2013",
    "The Carriage held but just Ourselves \u2013",
    "And Immortality.",
    "We slowly drove \u2013 He knew no haste",
    "And I had put away",
    "My labor and my leisure too,",
    "For His Civility \u2013",
    "We passed the School, where Children strove",
    "At Recess \u2013 in the Ring \u2013",
    "We passed the Fields of Gazing Grain \u2013",
    "We passed the Setting Sun \u2013",
    "Or rather \u2013 He passed Us \u2013",
    "The Dews drew quivering and Chill \u2013",
    "For only Gossamer, my Gown \u2013",
    "My Tippet \u2013 only Tulle \u2013",
    "We paused before a House that seemed",
    "A Swelling of the Ground \u2013",
    "The Roof was scarcely visible \u2013",
    "The Cornice \u2013 in the Ground \u2013",
    "Since then \u2013 'tis Centuries \u2013 and yet",
    "Feels shorter than the Day",
    "I first surmised the Horses' Heads",
    "Were toward Eternity \u2013"
  ],
  "title": "Because I could not stop for Death \u2013 (479)"
},
{
  "author": "Emily Dickinson",
  "text": [
    "The Soul has Bandaged moments -",
    "When too appalled to stir -",
    "She feels some ghastly Fright come up",
    "And stop to look at her -",
    "Salute her, with long fingers -",
    "Caress her freezing hair -",
    "Sip, Goblin, from the very lips",
    "The Lover - hovered - o'er -",
    "Unworthy, that a thought so mean",
    "Accost a Theme - so - fair -",
    "The soul has moments of escape -",
    "When bursting all the doors -",
    "She dances like a Bomb, abroad,",
    "And swings opon the Hours,",
    "As do the Bee - delirious borne -",
    "Long Dungeoned from his Rose -",
    "Touch Liberty - then know no more -",
    "But Noon, and Paradise",
    "The Soul's retaken moments -",
    "When, Felon led along,",
    "With shackles on the plumed feet,",
    "And staples, in the song,",
    "The Horror welcomes her, again,",
    "These, are not brayed of Tongue -"
  ],
  "title": "The Soul has Bandaged moments - (360)"
},
{
  "author": "Emily Dickinson",
  "text": [
    "Much Madness is divinest Sense -",
    "To a discerning Eye -",
    "Much Sense - the starkest Madness -",
    "\u2019Tis the Majority",
    "In this, as all, prevail -",
    "Assent - and you are sane -",
    "Demur - you\u2019re straightway dangerous -",
    "And handled with a Chain -"
  ],
  "title": "Much Madness is divinest Sense - (620)"
},
{
  "author": "Ezra Pound",
  "text": [
    "Four and forty lovers had Agathas in the old days,",
    "All of whom she refused;",
    "And now she turns to me seeking love,",
    "And her hair also is turning.",
    "I have fed your lar with poppies,",
    "I have adored you for three full years;",
    "And now you grumble because your dress does not fit",
    "And because I happen to say so.",
    "Memnon, Memnon, that lady",
    "Who used to walk about amongst us",
    "With such gracious uncertainty,",
    "Is now wedded",
    "To a British householder.",
    "Flawless as Aphrodite,",
    "Thoroughly beautiful,",
    "Brainless,",
    "The faint odor of your patchouli,",
    "Faint, almost, as the lines of cruelty about your chin,",
    "Assails me, and concerns me almost as little."
  ],
  "title": "Ladies"
},
{
  "author": "Ezra Pound",
  "text": [
    "While my hair was still cut straight across my forehead",
    "I played about the front gate, pulling flowers.",
    "You came by on bamboo stilts, playing horse,",
    "You walked about my seat, playing with blue plums.",
    "And we went on living in the village of Ch\u014dkan:",
    "Two small people, without dislike or suspicion.",
    "At fourteen I married My Lord you.",
    "I never laughed, being bashful.",
    "Lowering my head, I looked at the wall.",
    "Called to, a thousand times, I never looked back.",
    "At fifteen I stopped scowling,",
    "I desired my dust to be mingled with yours",
    "Forever and forever, and forever.",
    "Why should I climb the look out?",
    "At sixteen you departed",
    "You went into far Ku-t\u014d-en, by the river of swirling eddies,",
    "And you have been gone five months.",
    "The monkeys make sorrowful noise overhead.",
    "You dragged your feet when you went out.",
    "By the gate now, the moss is grown, the different mosses,",
    "Too deep to clear them away!",
    "The leaves fall early this autumn, in wind.",
    "The paired butterflies are already yellow with August",
    "Over the grass in the West garden;",
    "They hurt me.",
    "I grow older.",
    "If you are coming down through the narrows of the river Kiang,",
    "Please let me know beforehand,",
    "And I will come out to meet you",
    "As far as Ch\u014d-f\u016b-Sa."
  ],
  "title": "The River-Merchant\u2019s Wife: A Letter"
},
{
  "author": "Ezra Pound",
  "text": [
    "May I for my own self song's truth reckon,",
    "Journey's jargon, how I in harsh days",
    "Hardship endured oft.",
    "Bitter breast-cares have I abided,",
    "Known on my keel many a care's hold,",
    "And dire sea-surge, and there I oft spent",
    "Narrow nightwatch nigh the ship's head",
    "While she tossed close to cliffs. Coldly afflicted,",
    "My feet were by frost benumbed.",
    "Chill its chains are; chafing sighs",
    "Hew my heart round and hunger begot",
    "Mere-weary mood. Lest man know not",
    "That he on dry land loveliest liveth,",
    "List how I, care-wretched, on ice-cold sea,",
    "Weathered the winter, wretched outcast",
    "Deprived of my kinsmen;",
    "Hung with hard ice-flakes, where hail-scur flew,",
    "There I heard naught save the harsh sea",
    "And ice-cold wave, at whiles the swan cries,",
    "Did for my games the gannet's clamour,",
    "Sea-fowls, loudness was for me laughter,",
    "The mews' singing all my mead-drink.",
    "Storms, on the stone-cliffs beaten, fell on the stern",
    "In icy feathers; full oft the eagle screamed",
    "With spray on his pinion.",
    "Not any protector",
    "May make merry man faring needy.",
    "This he little believes, who aye in winsome life",
    "Abides 'mid burghers some heavy business,",
    "Wealthy and wine-flushed, how I weary oft",
    "Must bide above brine.",
    "Neareth nightshade, snoweth from north,",
    "Frost froze the land, hail fell on earth then",
    "Corn of the coldest. Nathless there knocketh now",
    "The heart's thought that I on high streams",
    "The salt-wavy tumult traverse alone.",
    "Moaneth alway my mind's lust",
    "That I fare forth, that I afar hence",
    "Seek out a foreign fastness.",
    "For this there's no mood-lofty man over earth's midst,",
    "Not though he be given his good, but will have in his youth greed;",
    "Nor his deed to the daring, nor his king to the faithful",
    "But shall have his sorrow for sea-fare",
    "Whatever his lord will.",
    "He hath not heart for harping, nor in ring-having",
    "Nor winsomeness to wife, nor world's delight",
    "Nor any whit else save the wave's slash,",
    "Yet longing comes upon him to fare forth on the water.",
    "Bosque taketh blossom, cometh beauty of berries,",
    "Fields to fairness, land fares brisker,",
    "All this admonisheth man eager of mood,",
    "The heart turns to travel so that he then thinks",
    "On flood-ways to be far departing.",
    "Cuckoo calleth with gloomy crying,",
    "He singeth summerward, bodeth sorrow,",
    "The bitter heart's blood. Burgher knows not \u0097",
    "He the prosperous man \u0097 what some perform",
    "Where wandering them widest draweth.",
    "So that but now my heart burst from my breast-lock,",
    "My mood 'mid the mere-flood,",
    "Over the whale's acre, would wander wide.",
    "On earth's shelter cometh oft to me,",
    "Eager and ready, the crying lone-flyer,",
    "Whets for the whale-path the heart irresistibly,",
    "O'er tracks of ocean; seeing that anyhow",
    "My lord deems to me this dead life",
    "On loan and on land, I believe not",
    "That any earth-weal eternal standeth",
    "Save there be somewhat calamitous",
    "That, ere a man's tide go, turn it to twain.",
    "Disease or oldness or sword-hate",
    "Beats out the breath from doom-gripped body.",
    "And for this, every earl whatever, for those speaking after \u0097",
    "Laud of the living, boasteth some last word,",
    "That he will work ere he pass onward,",
    "Frame on the fair earth 'gainst foes his malice,",
    "Daring ado, ...",
    "So that all men shall honour him after",
    "And his laud beyond them remain 'mid the English,",
    "Aye, for ever, a lasting life's-blast,",
    "Delight mid the doughty.",
    "Days little durable,",
    "And all arrogance of earthen riches,",
    "There come now no kings nor C\u00e6sars",
    "Nor gold-giving lords like those gone.",
    "Howe'er in mirth most magnified,",
    "Whoe'er lived in life most lordliest,",
    "Drear all this excellence, delights undurable!",
    "Waneth the watch, but the world holdeth.",
    "Tomb hideth trouble. The blade is layed low.",
    "Earthly glory ageth and seareth.",
    "No man at all going the earth's gait,",
    "But age fares against him, his face paleth,",
    "Grey-haired he groaneth, knows gone companions,",
    "Lordly men are to earth o'ergiven,",
    "Nor may he then the flesh-cover, whose life ceaseth,",
    "Nor eat the sweet nor feel the sorry,",
    "Nor stir hand nor think in mid heart,",
    "And though he strew the grave with gold,",
    "His born brothers, their buried bodies",
    "Be an unlikely treasure hoard."
  ],
  "title": "The Seafarer"
}];

export default library;
